---
title: "supplementary_figure_8"
author: "M. Pohly"
date: "`r Sys.Date()`"
output: html_document
---

## Load libraries
```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(scran)
library(scater)
library(BiocParallel)
library(gridExtra)
library(ComplexHeatmap)
library(circlize)
library(ggbeeswarm)
library(readxl)
library(parallel)
library(edgeR)
library(ggridges)

ncores <- 10
mcparam <- MulticoreParam(workers=ncores)
register(mcparam)
```

## Define variables
```{r}
opt <- list()
opt$sce <- "data/submission/TFlow_split_complete.RDS"
opt$types <- "data/submission/TFlow_celltypes.csv"
opt$plot <- "plots/SFig9_10/"

## Set theme
lgd <-  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), 
        text = element_text(size = 15),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA), 
        legend.background = element_rect(fill='transparent',colour = NA), 
        strip.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

## Load data
```{r}
## Load single-cell experiment
sce <- readRDS(opt$sce)
sce <- sce[["unstim"]]

## Load cell type annotation
types <- read.csv(opt$types) %>%
  mutate(uniqueBarcode = as.character(uniqueBarcode)) %>%
  mutate(celltype_broad = ifelse(celltype %in% c("CD16- NK-cell", "CD16+ NK-cell"), "NK-Cells", celltype)) %>%
  mutate(celltype_broad = ifelse(celltype %in% c("T-reg", "gd T-cell", "naive CD4 T-cell", "naive CD8 T-cell", "CD8 T-emra", "CD8 effector memory T-cell", 
                                                 "CD8 central memory T-cell", "CD7+ memory CD4 T-emra", "CD7+ effector memory CD4 T-cell", 
                                                 "CD7+ central memory CD4 T-cell", "CD7- memory CD4 T-emra", "CD7- effector memory CD4 T-cell", 
                                                 "CD7- central memory CD4 T-cell"), "T-Cells", celltype_broad)) %>%
  mutate(celltype_broad = ifelse(celltype %in% c("naive B-cell", "memory B-cell"), "B-Cells", celltype_broad)) %>%
  mutate(celltype = ifelse(celltype %in% c("CD7- effector memory CD4 T-cell", "CD7+ effector memory CD4 T-cell"), "CD4 EM T-cell", celltype), 
         celltype = ifelse(celltype %in% c("CD7- central memory CD4 T-cell", "CD7+ central memory CD4 T-cell"), "CD4 CM T-cell", celltype), 
         celltype = ifelse(celltype %in% c("CD8 central memory T-cell"), "CD8 CM T-cell", celltype),
         celltype = ifelse(celltype %in% c("CD8 effector memory T-cell"), "CD8 EM T-cell", celltype),
         celltype = ifelse(celltype %in% c("CD7- effector memory CD4 T-cell", "CD7+ effector memory CD4 T-cell"), "CD4 EM T-cell", celltype),
         celltype = ifelse(celltype %in% c("CD7- memory CD4 T-emra", "CD7+ memory CD4 T-emra"), "CD4 T-emra", celltype))



ld <- 1.5
cl3 <- 2.5
cl3small <- 2.25
apo <- 1.45
il2 <- 1.5
tnf  <- 1.5
ifng <- 1.25
ki67 <- 1.5
gzmb <- 1.5
gmcsf <- 1.5
il10 <- 1.5
gzmb <- 1.5

```

#### Overview UMAPs
```{r}
plotTab <- ggcells(sce, features = c("SSCA", "LD", "Apotracker", "cleaved_caspase_3", "FSCA", "Time"), exprs_values = "exprs")[[1]]

## Randomly sample to reduce overplotting
set.seed(100)
plotTab <- plotTab[sample(1:nrow(plotTab), nrow(plotTab)), ]

## Plot cell types
p1 <- plotTab %>% 
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype), 
         Treatment %in% c("DMSO", "Birinapant", "Selinexor", "QVDOph", "Birinapant|QVDOph")) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = celltype)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("T-LGL" = "#A5D6A7", "T-PLL" = "#64B5F6","memory B-cell" = "#FFA000", 
                                 "naive B-cell" = "#FFD45F", "T-reg" = "#AD1457", "gd T-cell" = "#F44336",
                                 "CD16- NK-cell" = "grey70", "CD16+ NK-cell" = "grey40", "naive CD4 T-cell" = "#43A047", 
                                 "CD4 T-emra" = "#4DB6AC", "CD4 EM T-cell" = "#80DEEA", "CD4 CM T-cell" = "#283593",
                                 "naive CD8 T-cell" = "#F8BBD0", "CD8 T-emra" = "#AB47BC", "CD8 CM T-cell" = "#D1C4E9", 
                                 "CD8 EM T-cell" = "#9575CD"
                               ))

p1

ggsave(plot = p1, filename = paste0(opt$plot, "TFlow_umap_cellsubtypes.png"), 
       height = 15, width = 15, units = "cm")


## Plot patientID
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype), 
         Treatment %in% c("DMSO", "Birinapant", "Selinexor", "QVDOph", "Birinapant|QVDOph")) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = patientID)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none")
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_patients.png"), 
       height = 15, width = 15, units = "cm")


## Plot Diagnosis
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype), 
         Treatment %in% c("DMSO", "Birinapant", "Selinexor", "QVDOph", "Birinapant|QVDOph")) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = Diagnosis_simple)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("T-LGL" = "#A5D6A7", "T-PLL" = "#64B5F6","healthy" = "#FFA000"
                               ))
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_diagnosis.png"), 
       height = 15, width = 15, units = "cm")

```

#### Show the stimulated data set
```{r}
sce.stim <- readRDS(opt$sce)
sce.stim <- sce.stim[["stim"]]

sce.stim <- sce.stim[, !sce.stim$patientID == "P0436"]

plotTab <- ggcells(sce.stim, features = c("CD3", "FSCA", "SSCA", "Ki67", "Apotracker", "LD", "cleaved_caspase_3", 
                                     "IL2", "IL10", "TNF", "IFNg", "GMCSF"), exprs_values = "exprs")[[1]]


## Plot patientID
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = patientID)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none")
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_patients_stim.png"), 
       height = 15, width = 15, units = "cm")


## Plot Diagnosis
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = Treatment)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("DMSO_stim" = "grey70", "Birinapant_low_stim" = "#AD1457"
                               ))
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_treatment_stim.png"), 
       height = 15, width = 15, units = "cm")


## Plot Diagnosis
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = Diagnosis_simple)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("T-LGL" = "#A5D6A7", "T-PLL" = "#64B5F6","healthy" = "#FFA000"
                               ))
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_diagnosis_stim.png"), 
       height = 15, width = 15, units = "cm")


## Plot celltype
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
  #mutate(celltype_broad = ifelse(celltype_broad %in% c("T-PLL", "T-LGL"), "Lymphoma Cells", celltype_broad)) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = celltype_broad)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("T-LGL" = "#A5D6A7", "T-PLL" = "#64B5F6", "T-Cells" = "#0D47A1", "NK-Cells" = "#AB47BC",
                                     "B-Cells" = "#FFA000"#, "monocyte" = "#66BB6A""#F44336"
                               ))
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_celltype_stim.png"), 
       height = 15, width = 15, units = "cm")

## Plot celltype
p <- plotTab %>%
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
  mutate(celltype_broad = ifelse(celltype_broad %in% c("T-PLL", "T-LGL"), "Lymphoma Cells", celltype_broad)) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = celltype)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd + #scale_colour_viridis_c() +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("T-LGL" = "#A5D6A7", "T-PLL" = "#64B5F6","memory B-cell" = "#FFA000", 
                                 "naive B-cell" = "#FFD45F", "T-reg" = "#AD1457", "gd T-cell" = "#F44336",
                                 "CD16- NK-cell" = "grey70", "CD16+ NK-cell" = "grey40", "naive CD4 T-cell" = "#43A047", 
                                 "CD4 T-emra" = "#4DB6AC", "CD4 EM T-cell" = "#80DEEA", "CD4 CM T-cell" = "#283593",
                                 "naive CD8 T-cell" = "#F8BBD0", "CD8 T-emra" = "#AB47BC", "CD8 CM T-cell" = "#D1C4E9", 
                                 "CD8 EM T-cell" = "#9575CD"
                               ))
p

ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_cellsubtype_stim.png"), 
       height = 15, width = 15, units = "cm")


p1 <- plotTab %>% 
  filter(!is.na(UMAP_FSCA.1)) %>%
  left_join(types, by = "uniqueBarcode") %>%
  filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
  mutate(#cellDeath = ifelse(LD > 1.5 |  cleaved_caspase_3 > 3 | Apotracker > 1.3, "dead", "live"),
         #cellDeath = ifelse(FSCA < 1000000 & patientID != "PID2160", "dead", cellDeath),
         #cellDeath = ifelse(cellDeath == "dead" & cleaved_caspase_3 > 3, "apoptotic", cellDeath)
         celltype_broad = ifelse(LD > ld | cleaved_caspase_3 > cl3 | Apotracker > apo, "dead", "live"), #1.45
         celltype_broad = ifelse(FSCA < 750000, "dead", celltype_broad),
         celltype_broad = ifelse(FSCA < 1500000 & cleaved_caspase_3 > cl3, "apoptotic", celltype_broad),
         celltype_broad = ifelse(celltype == "dead" & cleaved_caspase_3 > cl3, "apoptotic", celltype_broad)) %>%
  ggplot(aes(x = UMAP_FSCA.1, y = UMAP_FSCA.2, colour = celltype_broad)) +
  geom_point(size = 0.1) +
  xlab("UMAP1") + ylab("UMAP2") +
  lgd +
  theme_void() +
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        legend.position = "none") +
  scale_colour_manual(values = c("live" = "#A5D6A7","apoptotic" = "#FFA000", 
                                "dead" = "#F44336"
                               ))
p1

ggsave(plot = p1, filename = paste0(opt$plot, "TFlow_umap_celldeath_stim.png"), 
       height = 15, width = 15, units = "cm")


brc.live <- plotTab %>%
    left_join(types, by = "uniqueBarcode") %>% 
   mutate(#cellDeath = ifelse(LD > 1.5 |  cleaved_caspase_3 > 3 | Apotracker > 1.3, "dead", "live"),
         #cellDeath = ifelse(FSCA < 1000000 & patientID != "PID2160", "dead", cellDeath),
         #cellDeath = ifelse(cellDeath == "dead" & cleaved_caspase_3 > 3, "apoptotic", cellDeath)
         cellDeath = ifelse(LD > ld |  cleaved_caspase_3 > cl3 | Apotracker > apo, "dead", "live"),
         cellDeath = ifelse(FSCA < 750000, "dead", cellDeath),
         cellDeath = ifelse(FSCA < 1500000 & cleaved_caspase_3 > cl3small, "apoptotic", cellDeath),
         cellDeath = ifelse(cellDeath == "dead" & cleaved_caspase_3 > cl3, "apoptotic", cellDeath)) %>%
  filter(cellDeath %in% c("live")) %>%
  pull(uniqueBarcode) %>% unique()


```

####
```{r}
sce.x <- sce.stim
compDrug <- c("Birinapant_low_stim")


colData(sce.x) <- colData(sce.x) %>%
  data.frame() %>%
  left_join(types, by = "uniqueBarcode") %>%
  mutate(Treatment = factor(Treatment, levels = c("DMSO_stim", compDrug)), 
         cluster_id = celltype_broad, 
         celltype_broad = ifelse(celltype_broad %in% c("T-PLL", "T-LGL"), "Lymphoma Cells", celltype_broad)) %>%
  DataFrame()

testTreat <- c("Birinapant_low_stim")
cellSub <- c("Lymphoma Cells", "T-Cells", "B-Cells", "NK-Cells")
adtSub <- c("IL2", "IL10", "GMCSF", "TNF", "IFNg")

## For some reason it still thinks there are NAs
sce.x <- sce.x[, !is.na(sce.x$celltype_broad)]
sce.x <- sce.x[, sce.x$uniqueBarcode %in% brc.live]

avgTab <- lapply(testTreat, function(z) {
  message(paste0("Fitting model for ", z))
  lapply(cellSub, function(x) {
    message(paste0("Celltype ", x))
    
    sce.x <- sce.x[, sce.x$celltype_broad == x & sce.x$uniqueBarcode %in% brc.live]
    
    ## Set-up model formulas
    meta.df <- unique(dplyr::select(data.frame(colData(sce.x)), patientID, Treatment, Stimulation))
    design <- stats::model.matrix(~ patientID + Treatment, meta.df)
    frml <- diffcyt::createFormula(meta.df, cols_fixed = c("patientID", "Treatment"))
    
    ## Get median counts
    summed <- summarizeAssayByGroup(sce.x, ids = colData(sce.x)[,c("patientID", "Treatment")],
                                    statistics = "median", assay.type = "exprs") # get raw counts and sum them up
    colData(summed)$Treatment <- factor(colData(summed)$Treatment, levels = c("DMSO_stim", compDrug))
    
    mat <- assay(summed, "median") %>% as.matrix()
    colnames(mat) <- paste0(summed$patientID, ".", summed$Treatment)
    
    ## For every marker assemble the corresponding data frame and fit a linear model
    lapply(adtSub, function(u) {
      df <- data.frame(medianExpr = mat[u, ], patTreat = colnames(mat), ncells = summed$ncells) %>%
        separate(col = "patTreat", into = c("patientID", "Treatment"), sep = "\\.")
      
      testTab <- frml$data %>% left_join(df, by = c("patientID", "Treatment")) %>%
        #dplyr::rename(y = medianExpr) %>%
        mutate(Treatment = factor(Treatment, levels = c("DMSO_stim", compDrug)), 
               celltype = x, adt = u) %>%
        filter(!ncells < 100) %>% unique()
      testTab
      
     }) %>% bind_rows()
  }) %>% bind_rows()
}) %>% bind_rows() #%>% mutate(p.adj = p.adjust(p, method = "BH"))


##
lapply(c("T-Cells"), function(y) {
  lapply(c("IL2", "IL10", "TNF", "IFNg", "GMCSF"), function(x) {
  p <- avgTab %>%
    filter(adt == x) %>%
    mutate(Treatment = ifelse(Treatment == "DMSO_stim", "DMSO", "Birinapant"), 
           Treatment = factor(Treatment, levels = c("DMSO", "Birinapant"))) %>%
    ggplot(aes(x = Treatment, y = medianExpr, fill = Treatment)) +
    geom_boxplot(alpha = 0.6) +
    geom_line(linewidth = 0.25, aes(group = patientID)) +
    geom_beeswarm(size = 3, shape = 21, cex = 3) +
    xlab("") + ylab(paste0("Median Expr. of Living Cells")) + ggtitle(x) +
    lgd + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), 
              legend.position = "none", 
              text = element_text(size = 17.5), 
              panel.border = element_rect(linewidth = 1, fill = "transparent"), 
              axis.text = element_text(size = 17.5)) +
  scale_fill_manual(values = c("Birinapant" = "#AD1457", "DMSO" = "grey70")) +
      facet_wrap(. ~ celltype, nrow = 1)
  
  ggsave(plot = p, filename = paste0(opt$plot, x, "_median_expr.png"),
         height = 12, width = 30, units = "cm")
  p
})
})
```

#### Show histograms
```{r}
plotTab.1 <- ggcells(sce[, sce$Treatment %in% c("DMSO", "Birinapant")], features = c("FSCA", "Ki67", "IL2", "IL10", "TNF", "IFNg", "GMCSF", "LD", "cleaved_caspase_3", "Apotracker", "PD1"), exprs_values = "exprs")[[1]]
plotTab.2 <- ggcells(sce.stim, features = c("FSCA", "Ki67", "IL2", "IL10", "TNF", "IFNg", "GMCSF", "LD", "cleaved_caspase_3", "Apotracker", "PD1"), exprs_values = "exprs")[[1]]

plotTab <- rbind(plotTab.1, plotTab.2)

brc.live <- plotTab %>%
    left_join(types, by = "uniqueBarcode") %>% 
   mutate(#cellDeath = ifelse(LD > 1.5 |  cleaved_caspase_3 > 3 | Apotracker > 1.3, "dead", "live"),
         #cellDeath = ifelse(FSCA < 1000000 & patientID != "PID2160", "dead", cellDeath),
         #cellDeath = ifelse(cellDeath == "dead" & cleaved_caspase_3 > 3, "apoptotic", cellDeath)
         cellDeath = ifelse(LD > ld |  cleaved_caspase_3 > cl3 | Apotracker > apo, "dead", "live"),
         cellDeath = ifelse(FSCA < 750000, "dead", cellDeath),
         cellDeath = ifelse(FSCA < 1500000 & cleaved_caspase_3 > cl3small, "apoptotic", cellDeath),
         cellDeath = ifelse(cellDeath == "dead" & cleaved_caspase_3 > cl3, "apoptotic", cellDeath)) %>%
  filter(cellDeath %in% c("live")) %>%
  pull(uniqueBarcode) %>% unique()


lapply(c("IL2", "IL10", "TNF", "IFNg", "GMCSF"), function(x) {
  message(x)
  p <- plotTab %>%
    left_join(types, by = "uniqueBarcode") %>%
    filter(uniqueBarcode %in% brc.live, !celltype == "debris") %>%
    filter(Treatment %in% c("DMSO", "DMSO_stim", "Birinapant_low_stim")) %>%
    mutate(celltype_broad = ifelse(celltype_broad %in% c("T-PLL", "T-LGL"), "Lymphoma Cells", celltype_broad)) %>%
    #filter(celltype_broad == "Lymphoma Cells") %>%
    mutate(Treatment = ifelse(Treatment == "DMSO_stim", "DMSO (stim)", Treatment),
           Treatment = ifelse(Treatment == "Birinapant_low_stim", "Birinapant (stim)", Treatment),
           Treatment = factor(Treatment, levels = c("Birinapant (stim)", "DMSO (stim)", "DMSO"))) %>%
    pivot_longer(cols = x, names_to = "adt", values_to = "expr") %>%
    ggplot(aes(x = expr, y = Treatment, fill = Treatment)) +
    #geom_density(alpha = 0.8, colour = "black") +
    geom_density_ridges2(alpha = 0.8, colour = "black") +
    xlab(x) + ylab("") +
    lgd +
    theme(legend.position = "none", 
          panel.border = element_rect(linewidth = 1)) +
    facet_wrap(. ~ celltype_broad, nrow = 1) +
    scale_fill_manual(values = c("Birinapant (stim)" = "#AD1457", "DMSO (stim)" = "#FFA000", 
                                   "DMSO" = "grey70"))
  
    ggsave(plot = p, filename = paste0(opt$plot, x, "_viol.png"),
         height = 10, width = 30, units = "cm")
    
  p
})

lapply(c("Ki67"), function(x) {
  message(x)
  p <- plotTab %>%
    left_join(types, by = "uniqueBarcode") %>%
    filter(uniqueBarcode %in% brc.live, !celltype == "debris") %>%
    filter(Treatment %in% c("DMSO", "DMSO_stim", "Birinapant_low_stim")) %>%
    mutate(celltype_broad = ifelse(celltype_broad %in% c("T-PLL", "T-LGL"), "Lymphoma Cells", celltype_broad)) %>%
    #filter(celltype_broad == "Lymphoma Cells") %>%
    mutate(Treatment = ifelse(Treatment == "DMSO_stim", "DMSO (stim)", Treatment),
           Treatment = ifelse(Treatment == "Birinapant_low_stim", "Birinapant (stim)", Treatment),
           Treatment = factor(Treatment, levels = c("Birinapant (stim)", "DMSO (stim)", "DMSO"))) %>%
    pivot_longer(cols = x, names_to = "adt", values_to = "expr") %>%
    ggplot(aes(x = expr, y = Treatment, fill = Treatment)) +
    #geom_density(alpha = 0.8, colour = "black") +
    geom_density_ridges2(alpha = 0.8, colour = "black") +
    geom_vline(xintercept = 1.5, linetype = "dashed") +
    xlab(x) + ylab("") +
    lgd +
    theme(legend.position = "none", 
          panel.border = element_rect(linewidth = 1)) +
    facet_wrap(. ~ celltype_broad, nrow = 1) +
    scale_fill_manual(values = c("Birinapant (stim)" = "#AD1457", "DMSO (stim)" = "#FFA000", 
                                 "DMSO" = "grey70"))
  
    ggsave(plot = p, filename = paste0(opt$plot, x, "_viol.png"),
         height = 10, width = 30, units = "cm")
    
  p
})

## Show Ki67
lapply(c("DMSO", "Birinapant"), function(x) {
  pList <- lapply(c("B-Cells", "Lymphoma Cells", "NK-Cells", "T-Cells"), function(y) {

    x.min <- min(plotTab$LD)
    x.max <- max(plotTab$LD)

    y.min <- min(plotTab$Ki67)
    y.max <- max(plotTab$Ki67)

    p <- plotTab %>%
      #filter(uniqueBarcode %in% brc.live) %>%
      mutate(Treatment = ifelse(Treatment == "DMSO_stim", "DMSO", "Birinapant"),
             Treatment = factor(Treatment, levels = c("DMSO", "Birinapant"))) %>%
      filter(Treatment == x) %>%
      left_join(types, by = "uniqueBarcode") %>%
      filter(!celltype %in% c("debris"), !is.na(celltype)) %>%
      mutate(celltype_broad = ifelse(celltype_broad %in% c("T-PLL", "T-LGL"), "Lymphoma Cells", celltype_broad)) %>%
      filter(celltype_broad == y) %>%
      ggplot(aes(x = LD, y = Ki67)) +
      ggpointdensity::geom_pointdensity(size = 0.05, adjust = 5) +
      xlim(x.min, x.max) + ylim(y.min, y.max) +
      xlab("") + ylab("") + ggtitle(y) +
      scale_colour_viridis_c() +
      geom_hline(yintercept = 1.5, linetype = "dashed") +
      lgd + theme(legend.position = "none",
                  panel.background = element_rect(linewidth = 5, fill = "transparent"),
                  axis.ticks = element_blank(), axis.text = element_blank())

      ggsave(plot = p, filename = paste0(opt$plot, "TFlow_umap_ki67_", x, "_", y, "_stim.png"),
              height = 10, width = 10, units = "cm")
    p
  })
  # ggsave(plot = grid.arrange(grobs = pList, nrow = 1), filename = paste0(opt$plot, "TFlow_umap_ki67_", x, "_stim.png"),
  #      height = 12.5, width = 30, units = "cm")

#  grid.arrange(grobs = pList, nrow = 1)
})

```

