---
title: "Supplemental Figure 2"
author: "M. Pohly"
date: "`r Sys.Date()`"
output: html_document
---

#### Load libraries
```{r warning=FALSE, message=FALSE}
library(readxl)
library(tidyverse)
library(jyluMisc)
library(DrugScreenExplorer)
library(ComplexHeatmap)
library(ggrepel)
library(parallel)
library(gridExtra)
library(knitr)
```

#### Define variables
```{r}
opt <- list()
opt$drugscreen <- "data/submission/drugScreens_pseudo.RDS"
opt$druganno <- "misc/drugList_suppl.xlsx"
opt$plot <- "plots/SFig2/"

## Set theme
lgd <-  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), 
        text = element_text(size = 15),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA), 
        legend.background = element_rect(fill='transparent',colour = NA), 
        strip.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
```

#### Load drug screen data and annotations
```{r}
drugList <- readRDS(opt$drugscreen)
drugAnno <- read_excel(opt$druganno) %>%
  dplyr::select(-Supplier, -Screen) %>% unique()
```

## Analysis
#### Dose-response verdinexor
```{r fig.height= 5, fig.width=6.5}
embl2016 <- drugList[["ScreenB"]]

drugSub <- "Verdinexor"

concInter <- embl2016 %>%
  dplyr::filter(name %in% c(drugSub), 
         diagnosis == "T-PLL") %>%
  dplyr::select(conc) %>% unique() %>% unlist() %>% 
  as.vector()
concInter[1:2] <- round(concInter[1:2], 1)
concInter[3:6] <- round(concInter[3:6], 2)
concInter[7:9] <- round(concInter[7:9], 3)

p1 <- embl2016 %>% 
  dplyr::filter(name %in% c(drugSub), 
         diagnosis == "T-PLL") %>%
  ggplot(aes(x = conc, y = viab, group = sampleID)) +
  geom_line(size = 0.25) + 
  geom_point(size = 3.75, shape = 21, fill = "#64B5F6") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  scale_y_continuous(limits = c(0, 1.2)) +
  scale_x_log10(labels = concInter, 
                breaks = concInter) +
  xlab("Concentration (µM)") + ylab("Viability") + 
  theme_classic() + ggtitle(paste("Screen B", drugSub, sep = " - ")) +
  theme(text = element_text(size = 17.5), 
        legend.key = element_blank(),
        plot.title = element_text(hjust=0.5),
        # axis.text.x = element_text(hjust = 1, angle = 45),
        axis.text = element_text(size = 17.5),
        axis.line = element_line(linewidth = 0.75),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))
p1

ggsave(plot = p1, filename = paste0(opt$plot, drugSub, ".png"), 
       height = 5.25, width = 7)
```

#### Dose-response ruxolitinib
```{r fig.height= 5, fig.width=6.5}
drugSub <- "Ruxolitinib"

concInter <- embl2016 %>%
  dplyr::filter(name %in% c(drugSub), 
         diagnosis == "T-PLL") %>%
  dplyr::select(conc) %>% unique() %>% unlist() %>% 
  as.vector()
concInter[1:2] <- round(concInter[1:2], 1)
concInter[3:6] <- round(concInter[3:6], 2)
concInter[7:9] <- round(concInter[7:9], 3)

p1 <- embl2016 %>% 
  dplyr::filter(name %in% c(drugSub), 
         diagnosis == "T-PLL") %>%
  ggplot(aes(x = conc, y = viab, group = sampleID)) +
  geom_line(size = 0.25) + 
  geom_point(size = 3.75, shape = 21, fill = "#64B5F6") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  scale_y_continuous(limits = c(0, 1.2)) +
  scale_x_log10(labels = concInter, 
                breaks = concInter) +
  xlab("Concentration (µM)") + ylab("Viability") + 
  theme_classic() + ggtitle(paste("Screen B", drugSub, sep = " - ")) +
  theme(text = element_text(size = 17.5), 
        legend.key = element_blank(),
        plot.title = element_text(hjust=0.5),
        # axis.text.x = element_text(hjust = 1, angle = 45),
        axis.text = element_text(size = 17.5),
        axis.line = element_line(linewidth = 0.75),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))
p1

ggsave(plot = p1, filename = paste0(opt$plot, drugSub, ".png"), 
       height = 5.25, width = 7)
```

#### Dose-response duvelisb
```{r fig.height= 5, fig.width=6.5}
drugSub <- "Duvelisib"

concInter <- embl2016 %>%
  dplyr::filter(name %in% c(drugSub), 
         diagnosis == "T-PLL") %>%
  dplyr::select(conc) %>% unique() %>% unlist() %>% 
  as.vector()
concInter[1:2] <- round(concInter[1:2], 1)
concInter[3:6] <- round(concInter[3:6], 2)
concInter[7:9] <- round(concInter[7:9], 3)

p1 <- embl2016 %>% 
  dplyr::filter(name %in% c(drugSub), 
         diagnosis == "T-PLL") %>%
  ggplot(aes(x = conc, y = viab, group = sampleID)) +
  geom_line(size = 0.25) + 
  geom_point(size = 3.75, shape = 21, fill = "#64B5F6") +
  geom_hline(yintercept = 1, linetype = "dashed") +
  scale_y_continuous(limits = c(0, 1.2)) +
  scale_x_log10(labels = concInter, 
                breaks = concInter) +
  xlab("Concentration (µM)") + ylab("Viability") + 
  theme_classic() + ggtitle(paste("Screen B", drugSub, sep = " - ")) +
  theme(text = element_text(size = 17.5), 
        legend.key = element_blank(),
        plot.title = element_text(hjust=0.5),
        # axis.text.x = element_text(hjust = 1, angle = 45),
        axis.text = element_text(size = 17.5),
        axis.line = element_line(linewidth = 0.75),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))
p1

ggsave(plot = p1, filename = paste0(opt$plot, drugSub, ".png"), 
       height = 5.25, width = 7)
```


#### Show reproducibility
```{r fig.height = 5.5, fig.width = 5.5, warning=FALSE, message=FALSE}
diagList <- c("T-PLL")

screenNames <- c("ScreenB", "ScreenC", "ScreenD", "ScreenA", "ScreenE")

pList <- lapply(diagList, function(x) {
  pList <- lapply(screenNames, function(y) {
    screenData <- drugList[[y]]
    
    screenData <- screenData %>% #filter(diagnosis == x) %>%
      group_by(diagnosis, patientID, name) %>%
      summarise(viab.auc = mean(normVal, na.rm = TRUE)) %>%
      ungroup()
    
    screenNamesOther <- screenNames[which(screenNames != y)]
    
    pList <- lapply(screenNamesOther, function(z) {
      screenDataOther <- drugList[[z]]
    
      screenDataOther <- screenDataOther %>% #filter(diagnosis == x) %>%
        group_by(diagnosis, patientID, name) %>%
        summarise(viab.auc.other = mean(normVal, na.rm = TRUE)) %>%
        ungroup()
      
      ## Intersect the patients
      patOver <- intersect(screenData$patientID, screenDataOther$patientID) %>% unique()
      message("Found ", length(patOver), " overlapping patients")
      
      ## Intersect the drugs
      drugOver <- intersect(screenData$name, screenDataOther$name) %>% unique()
      message("Found ", length(drugOver), " overlapping drugs")
      
      ## Plot overlap
      p <- screenData %>%
        filter(patientID %in% patOver, name %in% drugOver) %>%
        left_join(screenDataOther, by = c("name", "patientID", "diagnosis")) %>%
        ggplot(aes(x = viab.auc, y = viab.auc.other, fill = diagnosis)) +
        geom_point(size = 2, shape = 21) +
        geom_smooth(method = "lm", colour = "black", fill = "grey80") +
        xlab(paste0(gsub(x = y, pattern = "Screen", replacement = "Screen "))) +
        ylab(paste0(gsub(x = z, pattern = "Screen", replacement = "Screen "))) +
        xlim(0, 1.6) + ylim(0, 1.6) +
        #ggtitle(paste0("Drug-Drug corr. ", y, " vs ", z)) +
        lgd +
        theme(legend.position = "none", 
              panel.border = element_rect(linewidth = 1, fill = "transparent")) +
        scale_fill_manual(values = c("MCL" = "#F44336", "T-PLL" = "#64B5F6", "CLL" = "#FFD45F"))
      
      ggsave(plot = p, filename = paste0(opt$plot, "/screen_corr/", x, "_", y, "_", z, ".png"), 
             height = 7, width = 7.5, units = "cm")
      p
    })
    #grid.arrange(grobs = pList, ncol = 1)
    names(pList) <- screenNamesOther
    pList
  }) 
  names(pList) <- screenNames
  pList
})
names(pList) <- diagList

pList

screenNames
## Give R2 and p.adj
cor.df.all <- lapply(diagList, function(x) {
  lapply(screenNames, function(y) {
    screenData <- drugList[[y]]
    
    screenData <- screenData %>% #filter(diagnosis == x) %>%
      group_by(diagnosis, patientID, name) %>%
      summarise(viab.auc = mean(normVal, na.rm = TRUE)) %>%
      ungroup()
    
    screenNamesOther <- screenNames[which(screenNames != y)]
    
    lapply(screenNames, function(z) {
      screenDataOther <- drugList[[z]]
    
      screenDataOther <- screenDataOther %>% #filter(diagnosis == x) %>%
        group_by(diagnosis, patientID, name) %>%
        summarise(viab.auc.other = mean(normVal, na.rm = TRUE)) %>%
        ungroup()
      
      ## Intersect the patients
      patOver <- intersect(screenData$patientID, screenDataOther$patientID) %>% unique()
      message("Found ", length(patOver), " overlapping patients")
      
      ## Intersect the drugs
      drugOver <- intersect(screenData$name, screenDataOther$name) %>% unique()
      message("Found ", length(drugOver), " overlapping drugs")
      
      ## Plot overlap
      cor.df <- screenData %>%
        filter(patientID %in% patOver, name %in% drugOver) %>%
        left_join(screenDataOther, by = c("name", "patientID", "diagnosis")) %>%
        #group_by(name) %>%
        nest() %>%
        mutate(m = map(data, ~cor.test(~viab.auc+viab.auc.other,.))) %>%
        mutate(res = map(m, broom::tidy)) %>%
        unnest(res) %>% ungroup() %>%
        select(estimate, p.value ) %>%
        arrange(p.value)
      cor.df$screen1 <- y
      cor.df$screen2 <- z
      cor.df
    }) %>% bind_rows()
  }) %>% bind_rows()
}) %>% bind_rows() %>% mutate(p.adj = p.adjust(p.value, method = "BH"))

kable(cor.df.all %>% arrange(p.adj))
#View(cor.df.all)
max(cor.df.all$p.adj)
range(cor.df.all[cor.df.all$estimate < 0.99, ]$estimate)

## Also per drug
cor.df <- lapply(diagList, function(x) {
  lapply(screenNames, function(y) {
    screenData <- drugList[[y]]
    
    screenData <- screenData %>% #filter(diagnosis == x) %>%
      group_by(diagnosis, patientID, name) %>%
      summarise(viab.auc = mean(normVal, na.rm = TRUE)) %>%
      ungroup()
    
    screenNamesOther <- screenNames[which(screenNames != y)]
    
    lapply(screenNamesOther, function(z) {
      screenDataOther <- drugList[[z]]
    
      screenDataOther <- screenDataOther %>% #filter(diagnosis == x) %>%
        group_by(diagnosis, patientID, name) %>%
        summarise(viab.auc.other = mean(normVal, na.rm = TRUE)) %>%
        ungroup()
      
      ## Intersect the patients
      patOver <- intersect(screenData$patientID, screenDataOther$patientID) %>% unique()
      message("Found ", length(patOver), " overlapping patients")
      
      ## Intersect the drugs
      drugOver <- intersect(screenData$name, screenDataOther$name) %>% unique()
      message("Found ", length(drugOver), " overlapping drugs")
      
      ## Plot overlap
      cor.df <- screenData %>%
        filter(patientID %in% patOver, name %in% drugOver) %>%
        left_join(screenDataOther, by = c("name", "patientID", "diagnosis")) %>%
        group_by(name) %>%
        nest() %>%
        mutate(m = map(data, ~cor.test(~viab.auc+viab.auc.other,.))) %>%
        mutate(res = map(m, broom::tidy)) %>%
        unnest(res) %>% ungroup() %>%
        select(name, estimate, p.value ) %>%
        arrange(p.value) 
      cor.df$screen1 <- y
      cor.df$screen2 <- z
      
      cor.df
    }) %>% bind_rows()
  }) %>% bind_rows()
}) %>% bind_rows() %>% mutate(p.adj = p.adjust(p.value, method = "BH"))
cor.df %>% filter(name %in% c("Birinapant", "Selinexor"))

```

#### Output session info
```{r pressure, echo=FALSE}
sessionInfo()
```

